# Generated by Django 4.2 on 2023-05-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('AboutMe', models.TextField(max_length=200)),
                ('Aim', models.TextField(max_length=200)),
                ('Background', models.TextField(max_length=200)),
                ('Approach', models.TextField(max_length=200)),
            ],
        ),
    ]
