# Generated by Django 4.2 on 2023-08-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leaveAReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=100)),
                ('year_group', models.CharField(blank=True, max_length=10)),
                ('predicted_grade', models.CharField(blank=True, max_length=5)),
                ('achieved_grade', models.CharField(blank=True, max_length=5)),
                ('star_rating', models.IntegerField(blank=True)),
                ('feedback_comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('passcode', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='leaveAReviewText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(max_length=800)),
            ],
        ),
    ]
