# Generated by Django 4.2 on 2023-08-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leaveAReview',
            new_name='reviews',
        ),
    ]
